const { expect } = require("chai");
const { ethers } = require("hardhat");
const { loadFixture } = require("@nomicfoundation/hardhat-network-helpers");
const { deployCoreEcosystemFixture } = require("./helpers/setup");

describe("01 - Factory System", function () {
    describe("Deployment & Creator Tracking", function () {
        it("Should fail to deploy a clone if user has no ERC20 allowance", async function () {
            const { deployerFacet, creator } = await loadFixture(deployCoreEcosystemFixture);
            await expect(
                deployerFacet.connect(creator).deployContract("TestNFT", "TNFT")
            ).to.be.revertedWith("Deployer: Not allowed to transfer tokens");
        });

        it("Should successfully deploy a RAIR721 clone, charge ERC20, and map ownership", async function () {
            const { deployerFacet, adminFacet, erc20, creator } = await loadFixture(deployCoreEcosystemFixture);
            const deployCost = await adminFacet.getDeploymentCost();
            await erc20.transfer(creator.address, deployCost);
            await erc20.connect(creator).approve(deployerFacet.address, deployCost);

            await expect(deployerFacet.connect(creator).deployContract("MyNFT", "MNFT"))
                .to.emit(deployerFacet, "DeployedContract");

            expect(await erc20.balanceOf(creator.address)).to.equal(0);
            expect(await deployerFacet.getCreatorsCount()).to.equal(1);
            expect(await deployerFacet.getContractCountOf(creator.address)).to.equal(1);
            
            const deployedList = await deployerFacet.creatorToContractList(creator.address);
            expect(deployedList.length).to.equal(1);
            expect(await deployerFacet.contractToCreator(deployedList[0])).to.equal(creator.address);
        });
    });

    describe("Points & Credit System", function () {
        it("Should allow users to deposit ERC20 for points", async function () {
            const { pointsFacet, erc20, buyer } = await loadFixture(deployCoreEcosystemFixture);
            await erc20.transfer(buyer.address, 500);
            await erc20.connect(buyer).approve(pointsFacet.address, 500);

            await expect(pointsFacet.connect(buyer).depositTokens(500))
                .to.emit(pointsFacet, "ReceivedTokens")
                .withArgs(buyer.address, erc20.address, 500, 500);

            expect(await pointsFacet.getUserPoints(buyer.address)).to.equal(500);
            expect(await pointsFacet.getTotalUserPoints(buyer.address)).to.equal(500);
        });
    });

    describe("Points Cryptographic Withdrawals", function () {
        it("Should allow a user to withdraw points with a valid signature from an authorized signer", async function () {
            const { pointsFacet, erc20, owner, buyer } = await loadFixture(deployCoreEcosystemFixture);

            const WITHDRAW_SIGNER_ROLE = await pointsFacet.WITHDRAW_SIGNER();
            await pointsFacet.grantRole(WITHDRAW_SIGNER_ROLE, owner.address);

            await erc20.transfer(buyer.address, 1000);
            await erc20.connect(buyer).approve(pointsFacet.address, 1000);
            await pointsFacet.connect(buyer).depositTokens(1000);

            const withdrawAmount = 400;
            const withdrawHash = await pointsFacet.getWithdrawHash(buyer.address, erc20.address, withdrawAmount);
            const signature = await owner.signMessage(ethers.utils.arrayify(withdrawHash));

            const initialContractBalance = await erc20.balanceOf(pointsFacet.address);
            const initialBuyerBalance = await erc20.balanceOf(buyer.address);

            await expect(pointsFacet.connect(buyer).withdraw(withdrawAmount, signature))
                .to.emit(pointsFacet, "WithdrewPoints")
                .withArgs(buyer.address, erc20.address, withdrawAmount);

            expect(await pointsFacet.getUserPoints(buyer.address)).to.equal(600);
            expect(await erc20.balanceOf(pointsFacet.address)).to.equal(initialContractBalance.sub(withdrawAmount));
            expect(await erc20.balanceOf(buyer.address)).to.equal(initialBuyerBalance.add(withdrawAmount));
        });

        it("Should reject withdrawal if the signature is generated by an unauthorized address", async function () {
            const { pointsFacet, erc20, buyer } = await loadFixture(deployCoreEcosystemFixture);

            await erc20.transfer(buyer.address, 500);
            await erc20.connect(buyer).approve(pointsFacet.address, 500);
            await pointsFacet.connect(buyer).depositTokens(500);

            const withdrawAmount = 200;
            const withdrawHash = await pointsFacet.getWithdrawHash(buyer.address, erc20.address, withdrawAmount);
            const unauthorizedSignature = await buyer.signMessage(ethers.utils.arrayify(withdrawHash));

            await expect(
                pointsFacet.connect(buyer).withdraw(withdrawAmount, unauthorizedSignature)
            ).to.be.revertedWith("PointsWithdraw: Invalid withdraw request");
        });

        it("Should prevent a withdrawal if the user requests an amount exceeding their point balance", async function () {
            const { pointsFacet, erc20, buyer } = await loadFixture(deployCoreEcosystemFixture);

            await erc20.transfer(buyer.address, 100);
            await erc20.connect(buyer).approve(pointsFacet.address, 100);
            await pointsFacet.connect(buyer).depositTokens(100);

            await expect(
                pointsFacet.getWithdrawHash(buyer.address, erc20.address, 200)
            ).to.be.revertedWith("PointsWithdraw: Invalid withdraw amount");
        });
    });
});